### ISSUE TITLE
Creating a working docker image

### ISSUE THREAD

**Issue by thebennos** [TeamHG-Memex/undercrawler#60]
Here is an example dockerfile. 
https://github.com/TeamHG-Memex/undercrawler/blob/dockerize-with-arachnado/Dockerfile

1. I created an arachnado image as base for undercrawler
2. with the example above I have created my undercrawler image. 

I can run undercrawler over commandline, but it looks that it not integrated in arachnado's UI and API. 

Every created crawl job over the UI or API from arachnado uses the (generic) arachnado crawler and not undercrawler and splash. 

I think something is missing to get both working together.

**Comment by lopuhin** [comment]
@thebennos the steps to get it to work are described here: https://github.com/TeamHG-Memex/undercrawler/blob/ba99c7527f006780201678e8a2345e735eb9d336/undercrawler-arachnado/README.md - you need to check out the dockerize-with-arachnado branch as it contains some fixes, and the arachnado revision that used to work is 1d2222b1f9c5c9ce95bb97a7d5d0a9d8436377bb (I don't think anything should have broken in arachando master though)

The branch was not merged because of some other pending issue that was resolved since then.
I hope to check if it still works early next week.

**Comment by thebennos** [comment]
hey
I followed exactly the readme. 
I made some smaller changes in the configs(internal DNS Link to MongoDB), because we can not use docker compose, we use DC/OS. 

SPLASH_URL  is provided as Enviroment variable.
Shoul I provide you some Logs? or my fork? or the docker Image?

**Comment by thebennos** [comment]
Got it working. 

The arachnado.conf need to be in the cmd in the dockerfile 
Like "arachnado --config ./arachnado.conf"

**Comment by lopuhin** [comment]
Glad you solved it @thebennos ! I'll keep the issue open to merge the branch.

**Comment by lopuhin** [comment]
The branch was merged some time ago here #56, closing
